### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by Sparkpin** [Sparkpin/Panda3DCraft#1]
- [x] Implement basic gameplay
- [ ] Implement player and physics
- [ ] Implement basic blocks
-- [x] Dirt
-- [ ] Sand
-- [ ] Gravel
-- [ ] Grass
-- [ ] Bricks
-- [ ] Glass
-- [ ] Wood
-- [ ] Leaves
- [ ] Implement inventory
- [ ] Basic world generation
- [ ] Mobs
- [ ] Survival

More to be added.
